### ISSUE TITLE
feature request: bam splitting by HP tag

### ISSUE THREAD

**Issue by maxibor** [bluenote-1577/floria#4]
Hey @bluenote-1577 ,
Floria looks like a very promising tool !
One feature that would be very nice to have would be the splitting of the bam file generated by `scripts/haplotag_output_dir.py` by hapolotypes using the HP tag.

For example, from `mapped.bam`, you would get `mapped_hp1.bam`, `mapped_hp[...].bam`, `mapped_hpn.bam`

**Comment by maxibor** [comment]
The use case I had in mind was for calling the consensus sequence by strain.
But maybe you have a better way of doing this ?

**Comment by bluenote-1577** [comment]
Hi @maxibor,

That's a reasonable thing to do...  see the script `scripts/get_bam_partition.py` that I tested quickly and seems to work. It can be used like this:

`python scripts/get_bam_partition.py -b all_reads.bam -t contig1.haplosets contig2.haplosets -p some_dir/`

and should split the files into something like 0.bam, 1.bam, 2.bam for each haploset index 0,1,2

let me know if it works for you
